kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-a
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-b
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-c
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-d
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-e
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239
- apiVersion: v1
  kind: PersistentVolume
  metadata:
     name: pv-f
  spec:
          capacity:
             storage: 100Mi
          volumeMode: Filesystem   
          accessModes:
             - ReadWriteOnce
          persistentVolumeReclaimPolicy: Recycle
          storageClassName: nfs
          mountOptions:
                  - hard
                  - nfsvers=4.1
          nfs:
             path: /home/juniarto/nfs_share_1
             server: 192.168.1.239


   

               
